

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your_secret_key_here
      - DB_HOST=db
      - DB_NAME=inventory_db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
